### ISSUE TITLE
Error - Could not resolve module

### ISSUE THREAD

**Issue by msahajwani** [Timkor/nuxt-polyfill#1]
I installed the package using npm install nuxt-polyfill and added it to nuxt.config

However, when I try to run the app, I keep getting the error - cannot find module  nuxt-polyfill

It's installed correctly in node_modules - however, I don't think nuxt is looking for module in node_modules. Can you help?

**Comment by Timkor** [comment]
Yes I am sorry, it's because of a wrong `main` field in `package.json`. I will fix this very soon.

**Comment by Timkor** [comment]
Please install version 1.0.1 of `nuxt-polyfill`:
```
npm i nuxt-polyfill@1.0.1
```
This issue has now been fixed.
