### ISSUE TITLE
Question - How to use for IE 11 ?

### ISSUE THREAD

**Issue by nicolas-bonnel** [Timkor/nuxt-polyfill#2]
Hello,

I'm having hard time making my app run on IE 11. This module seems interesting, but I can't figure how to configure it.

My error on IE 11 is : "object doesn't support property or method from"

How can I configure your module to detect this error and import the correct polyfill ?

Thanks in advance !

**Comment by Timkor** [comment]
Hi,

Can you give me a more specific error message?

I guess it's about `Array.from`, but that strange because it should be polyfilled automatically by Nuxt since it uses `core-js`.

Can you also supply your `nuxt.config.js`?

**Comment by nicolas-bonnel** [comment]
Thanks for your feedback.

You're right, I had a bugged version of nuxt and core-js were not used. That's now ok and I begin to understand the use for your module : to load polyfills not supported with core-js.

I still have a problem : I need the url-polyfill because an URL object is created in the store, in a function init() called by a plugin. Using your module the url-polyfill plugin is loaded and added as a new plugin, I believe before my init plugin (you insert them with unshift), but is not yet loaded when the init execute.

Adding a `require('url-polyfill')` in my init plugin, before calling store action works, so I believe my problem is the loading order.

Another difference is that my init plugin is loaded server side, whereas your plugin is not, but my app is built in spa mode...

**Comment by Timkor** [comment]
Hi Nicolas,

You are right. This module put the polyfill plugins in front of the other plugins. But apparently Nuxt initialize all plugins with are rendered server side before.

This issue has now been fixed.

Try to use the URL polyfill only within the exported default function of your plugin:

```javascript
// URL is NOT available here yet.

export default () => {
    // URL is available here:
    new URL('https://google.nl');
}
```
