### ISSUE TITLE
Polyfill Object.entries

### ISSUE THREAD

**Issue by mornir** [Timkor/nuxt-polyfill#3]
Hi! First thank you for this awesome module. It makes polyfilling much easier.
I want to polyfill Object.entries, using this npm package:
https://www.npmjs.com/package/object.entries

What's wrong with my code?
```js
 {
        require: 'object.entries',
        detect: () => 'entries' in window.Object,
        install: entries => entries.shim(),
 }
```

**Comment by Timkor** [comment]
@mornir 
Thank you. 

Your code does look correct.

What error are you getting? Or what behaviour is not working for you?

**Comment by mornir** [comment]
In IE11, I still get the error `Object doesn't support property or method 'entries'` 🤔

**Comment by Timkor** [comment]
Can you try this and see if `shimmed` is logged into the console of IE11?
```
{
        require: 'object.entries',
        detect: () => 'entries' in window.Object,
        install: entries => {  
                entries.shim()
                console.log('shimmed')
        }
 }
```

**Comment by mornir** [comment]
No, it's not logged. 😕

I don't know if this information is useful: the method 'entries' is used in this package https://www.npmjs.com/package/vue2-google-maps, which I import as a Nuxt plugin.

If I import the polyfill via polyfill.io, it works.

**Comment by Timkor** [comment]
Can you post your Nuxt plugin here?

**Comment by mornir** [comment]
Here the repo: https://github.com/mornir/sounding-soil

**Comment by Timkor** [comment]
I made a pull request.

The polyfills are loaded subsequentially and only available in the default exported function of a plugin.

https://github.com/mornir/sounding-soil/pull/10

**Comment by mornir** [comment]
Awesome! It works! Thanks! 😃
